### PR TITLE
Adding a basic selection of settings for syncthing-bar

### PR DESCRIPTION
**Pull request by chrisidefix**
So far the settings allow you to configure the menu-bar icon (b/w, inverted b/w, color) and disable the confirmation upon exiting syncthing-bar. Settings are stored and read from the user preference folder. I also show the port number, but editing it doesn't do much - someone would have to extend upon that, if there is any need for actually editing the port number in this settings preference pane. Enjoy!

### CODE REVIEW

**Comment by chrisidefix** [comment]
Alright, so I also added stopping / restarting (pausing) of syncthing as requested in issue #12

**Comment by chrisidefix** [comment]
As suggested (by me) in issue #12, I also implemented an automatic detection of any running app that will trigger `syncthing` to pause. Once all the "trigger-applications" are no longer running, syncthing is restarted. This is optional and is OFF by default in the settings menu.

**Comment by m0ppers** [comment]
Thanks for the pull requests :D Just a quick notification: Seen it and it is on my todo list. Unfortunately i am currently in the middle of some release work for a customer and don't find time. Hopefully i will be able to have a look at it next week. Sorry for the delay :(

**Comment by chrisidefix** [comment]
No worries - whenever you find the time. Let me know if you spot any problems.

**Pull request merged**
